insert into brand (name) values ('2500');
insert into brand (name) values ('Range Rover Classic');
insert into brand (name) values ('Neon');
insert into brand (name) values ('3 Series');
insert into brand (name) values ('RDX');
insert into brand (name) values ('S10 Blazer');
insert into brand (name) values ('A6');
insert into brand (name) values ('9000');
insert into brand (name) values ('Sprinter');
insert into brand (name) values ('Mustang');
insert into brand (name) values ('CR-V');
insert into brand (name) values ('Camaro');
insert into brand (name) values ('Eclipse');
insert into brand (name) values ('240SX');
insert into brand (name) values ('Aventador');
insert into brand (name) values ('i-Series');
insert into brand (name) values ('Firebird');
insert into brand (name) values ('Marquis');
insert into brand (name) values ('Integra');
insert into brand (name) values ('Eos');
insert into brand (name) values ('Cayenne');
insert into brand (name) values ('Intrigue');
insert into brand (name) values ('Continental Mark VII');
insert into brand (name) values ('Golf');
insert into brand (name) values ('Navigator');
insert into brand (name) values ('Venture');
insert into brand (name) values ('Quest');
insert into brand (name) values ('Elantra');
insert into brand (name) values ('Jetta');
insert into brand (name) values ('Mazdaspeed 3');
insert into brand (name) values ('599 GTB Fiorano');
insert into brand (name) values ('R-Class');
insert into brand (name) values ('Forester');
insert into brand (name) values ('Camry');
insert into brand (name) values ('C70');
insert into brand (name) values ('Sportage');
insert into brand (name) values ('929');
insert into brand (name) values ('LS');
insert into brand (name) values ('Corvette');
insert into brand (name) values ('A4');
insert into brand (name) values ('Ranger');
insert into brand (name) values ('Spectra');
insert into brand (name) values ('Concorde');
insert into brand (name) values ('Vigor');
insert into brand (name) values ('5 Series');
insert into brand (name) values ('LeSabre');
insert into brand (name) values ('200SX');
insert into brand (name) values ('GTO');
insert into brand (name) values ('Suburban 1500');
insert into brand (name) values ('MR2');
insert into brand (name) values ('Express 1500');
insert into brand (name) values ('Protege');
insert into brand (name) values ('del Sol');
insert into brand (name) values ('Thunderbird');
insert into brand (name) values ('ES');
insert into brand (name) values ('5 Series');
insert into brand (name) values ('E-Series');
insert into brand (name) values ('S8');
insert into brand (name) values ('Insight');
insert into brand (name) values ('Express 2500');
insert into brand (name) values ('Intrepid');
insert into brand (name) values ('Mustang');
insert into brand (name) values ('SVX');
insert into brand (name) values ('Solara');
insert into brand (name) values ('GLK-Class');
insert into brand (name) values ('Truck');
insert into brand (name) values ('Land Cruiser');
insert into brand (name) values ('MKX');
insert into brand (name) values ('F150');
insert into brand (name) values ('Z4 M');
insert into brand (name) values ('Grand Prix');
insert into brand (name) values ('RAV4');
insert into brand (name) values ('Thunderbird');
insert into brand (name) values ('TL');
insert into brand (name) values ('Sienna');
insert into brand (name) values ('VS Commodore');
insert into brand (name) values ('626');
insert into brand (name) values ('Esteem');
insert into brand (name) values ('Corvette');
insert into brand (name) values ('Intrigue');
insert into brand (name) values ('Concorde');
insert into brand (name) values ('Century');
insert into brand (name) values ('CL');
insert into brand (name) values ('Skylark');
insert into brand (name) values ('E350');
insert into brand (name) values ('NSX');
insert into brand (name) values ('Citation');
insert into brand (name) values ('Escalade EXT');
insert into brand (name) values ('MKT');
insert into brand (name) values ('Sable');
insert into brand (name) values ('RX-8');
insert into brand (name) values ('Lumina');
insert into brand (name) values ('L300');
insert into brand (name) values ('4Runner');
insert into brand (name) values ('STS');
insert into brand (name) values ('Voyager');
insert into brand (name) values ('Aviator');
insert into brand (name) values ('Grand Caravan');
insert into brand (name) values ('400E');
insert into brand (name) values ('Suburban 1500');
insert into brand (name) values ('MPV');
insert into brand (name) values ('iQ');
insert into brand (name) values ('9-5');
insert into brand (name) values ('MX-5');
insert into brand (name) values ('SLX');
insert into brand (name) values ('RX');
insert into brand (name) values ('Ridgeline');
insert into brand (name) values ('Windstar');
insert into brand (name) values ('Camaro');
insert into brand (name) values ('Discovery');
insert into brand (name) values ('Vandura 1500');
insert into brand (name) values ('Firebird');
insert into brand (name) values ('Cube');
insert into brand (name) values ('Navajo');
insert into brand (name) values ('626');
insert into brand (name) values ('Sedona');
insert into brand (name) values ('SVX');
insert into brand (name) values ('Nitro');
insert into brand (name) values ('Paseo');
insert into brand (name) values ('3 Series');
insert into brand (name) values ('SJ');
insert into brand (name) values ('Aveo');
insert into brand (name) values ('Panamera');
insert into brand (name) values ('9000');
insert into brand (name) values ('Z4');
insert into brand (name) values ('TT');
insert into brand (name) values ('300M');
insert into brand (name) values ('Avalon');
insert into brand (name) values ('Sunbird');
insert into brand (name) values ('Esperante');
insert into brand (name) values ('Continental Flying Spur');
insert into brand (name) values ('Cutlass Supreme');
insert into brand (name) values ('Sidekick');
insert into brand (name) values ('Venture');
insert into brand (name) values ('Scirocco');
insert into brand (name) values ('QX');
insert into brand (name) values ('CL');
insert into brand (name) values ('Hemisfear');
insert into brand (name) values ('Liberty');
insert into brand (name) values ('Suburban 2500');
insert into brand (name) values ('Grand Caravan');
insert into brand (name) values ('GLI');
insert into brand (name) values ('Malibu');
insert into brand (name) values ('M3');
insert into brand (name) values ('F150');
insert into brand (name) values ('Intrepid');
insert into brand (name) values ('Q5');
insert into brand (name) values ('LS');
insert into brand (name) values ('VehiCROSS');
insert into brand (name) values ('GTI');
