insert into author_amazon (name, books, address) values ('Vanya Titchen', 21, '10783 Fuller Court');
insert into author_amazon (name, books, address) values ('Albrecht Dulanty', 43, '6394 Fremont Plaza');
insert into author_amazon (name, books, address) values ('Brittney Meffan', 6, '1 Lakeland Trail');
insert into author_amazon (name, books, address) values ('Erik Agus', 38, '5 Moland Lane');
insert into author_amazon (name, books, address) values ('Christa Saenz', 49, '714 Morning Way');
insert into author_amazon (name, books, address) values ('Zach Pear', 47, '91 Scofield Pass');
insert into author_amazon (name, books, address) values ('Clemence Wortley', 1, '2 Eagan Court');
insert into author_amazon (name, books, address) values ('Callean Lelande', 25, '484 Brown Park');
insert into author_amazon (name, books, address) values ('Johannah McAlindon', 7, '342 Dunning Crossing');
insert into author_amazon (name, books, address) values ('Ban Samudio', 10, '51 Manley Center');
insert into author_amazon (name, books, address) values ('Teresa Reese', 3, '2914 Toban Plaza');
insert into author_amazon (name, books, address) values ('Neddy Brachell', 3, '99 Derek Park');
insert into author_amazon (name, books, address) values ('Rosana Shovel', 25, '32 Clemons Hill');
insert into author_amazon (name, books, address) values ('Cherry Snary', 30, '9270 Lyons Circle');
insert into author_amazon (name, books, address) values ('Dode MacManus', 33, '9820 Kensington Parkway');
insert into author_amazon (name, books, address) values ('Sven Bulled', 23, '89 Morning Center');
insert into author_amazon (name, books, address) values ('Colline Shergill', 17, '8044 Center Circle');
insert into author_amazon (name, books, address) values ('El Losbie', 6, '07 Sutherland Crossing');
insert into author_amazon (name, books, address) values ('Mattheus Preon', 44, '89706 Sugar Avenue');
insert into author_amazon (name, books, address) values ('Twila Andress', 27, '78760 Autumn Leaf Pass');
insert into author_amazon (name, books, address) values ('Alisun Lillegard', 33, '1 Schmedeman Point');
insert into author_amazon (name, books, address) values ('Bili Seeler', 33, '2 Prairie Rose Trail');
insert into author_amazon (name, books, address) values ('Benn Chattell', 31, '449 Vahlen Court');
insert into author_amazon (name, books, address) values ('Mirelle Davitashvili', 41, '22 Clarendon Street');
insert into author_amazon (name, books, address) values ('Archibaldo Stiling', 21, '4566 Mockingbird Crossing');
insert into author_amazon (name, books, address) values ('Amby Adolphine', 14, '916 Sycamore Hill');
insert into author_amazon (name, books, address) values ('Orelia Loddon', 2, '36142 Stuart Road');
insert into author_amazon (name, books, address) values ('Wini Jenteau', 40, '2 American Park');
insert into author_amazon (name, books, address) values ('Jolynn MacAne', 29, '803 Hagan Street');
insert into author_amazon (name, books, address) values ('Emmey Brownjohn', 9, '50753 Bartillon Alley');
insert into author_amazon (name, books, address) values ('Ame Maciaszek', 25, '91 Comanche Parkway');
insert into author_amazon (name, books, address) values ('Arvy Ormond', 37, '0 Namekagon Pass');
insert into author_amazon (name, books, address) values ('Nikolas Baudon', 15, '1 Londonderry Trail');
insert into author_amazon (name, books, address) values ('Robbin Adaway', 42, '21282 Gulseth Terrace');
insert into author_amazon (name, books, address) values ('Jennilee Deme', 45, '72 Bonner Crossing');
insert into author_amazon (name, books, address) values ('Evita Girogetti', 46, '87531 Longview Alley');
insert into author_amazon (name, books, address) values ('Dolorita Rivilis', 33, '5 Oak Valley Street');
insert into author_amazon (name, books, address) values ('Townsend Rawsthorn', 40, '3 Bunker Hill Court');
insert into author_amazon (name, books, address) values ('Emelen Partrick', 13, '632 Mitchell Hill');
insert into author_amazon (name, books, address) values ('Dulce Cossans', 17, '044 John Wall Lane');
insert into author_amazon (name, books, address) values ('Silvia Lamey', 2, '348 Spohn Parkway');
insert into author_amazon (name, books, address) values ('Margette Vickar', 29, '59 Daystar Parkway');
insert into author_amazon (name, books, address) values ('Gardie Gorrie', 29, '4271 5th Way');
insert into author_amazon (name, books, address) values ('Heindrick Seeviour', 21, '2751 7th Parkway');
insert into author_amazon (name, books, address) values ('Minda Gooda', 45, '51687 Melrose Parkway');
insert into author_amazon (name, books, address) values ('Xever Propper', 34, '26 Maryland Park');
insert into author_amazon (name, books, address) values ('Blithe Feehely', 47, '1 Lyons Alley');
insert into author_amazon (name, books, address) values ('Louise Carreyette', 24, '54882 Homewood Crossing');
insert into author_amazon (name, books, address) values ('Torey Goodspeed', 50, '1443 Little Fleur Street');
insert into author_amazon (name, books, address) values ('Haskel Jamblin', 17, '21084 Meadow Vale Avenue');
