insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (45, '201.69', 'Iguana, common green', 39);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (42, '117.76', 'Praying mantis (unidentified)', 9);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (17, '178.65', 'Macaw, green-winged', 92);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (34, '142.39', 'Antelope ground squirrel', 54);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (11, '25.06', 'Southern lapwing', 21);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (47, '26.57', 'Savannah deer', 14);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (16, '302.17', 'Raccoon, common', 22);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (12, '263.24', 'White-winged dove', 16);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (41, '216.41', 'Shrike, common boubou', 57);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (3, '96.71', 'Common mynah', 78);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (48, '294.43', 'Cobra, cape', 43);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (45, '51.37', 'Francolin, swainson''s', 51);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (39, '146.46', 'Common turkey', 23);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (2, '145.85', 'Mountain goat', 28);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (43, '28.55', 'Genet, common', 16);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (29, '155.31', 'Great cormorant', 95);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (50, '130.82', 'Rhea, gray', 87);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (41, '243.03', 'Squirrel, red', 12);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (21, '271.84', 'Lapwing, southern', 66);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (48, '325.45', 'Eurasian badger', 81);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (32, '314.41', 'Mule deer', 62);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (36, '171.03', 'Dove, little brown', 83);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (38, '26.38', 'Indian giant squirrel', 94);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (24, '274.50', 'Weaver, red-billed buffalo', 23);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (2, '233.50', 'Butterfly (unidentified)', 51);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (9, '31.91', 'Painted stork', 78);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (14, '141.76', 'Fox, bat-eared', 61);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (31, '180.19', 'Hawk, red-tailed', 91);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (1, '317.33', 'Lizard, mexican beaded', 89);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (31, '181.74', 'Blue and yellow macaw', 34);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (23, '122.62', 'Short-nosed bandicoot', 52);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (26, '73.95', 'Desert tortoise', 49);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (2, '148.88', 'Chickadee, black-capped', 6);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (42, '232.12', 'Puma', 21);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (16, '210.55', 'Bird (unidentified)', 92);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (40, '314.79', 'Australian spiny anteater', 96);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (3, '66.24', 'Macaque, japanese', 79);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (25, '21.30', 'Shark, blue', 73);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (2, '230.11', 'Hawk, galapagos', 66);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (19, '212.22', 'Flicker, field', 31);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (41, '275.72', 'Red-knobbed coot', 46);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (12, '42.82', 'African clawless otter', 71);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (46, '75.42', 'Sloth, hoffman''s', 79);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (13, '77.47', 'Sandpiper, spotted wood', 90);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (32, '142.55', 'Flycatcher, tyrant', 79);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (29, '92.89', 'Secretary bird', 56);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (13, '34.56', 'Gull, pacific', 76);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (22, '79.40', 'Monitor, white-throated', 24);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (22, '80.62', 'Heron, yellow-crowned night', 42);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (2, '93.50', 'Egret, snowy', 4);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (20, '176.90', 'Caribou', 70);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (36, '295.47', 'Glider, feathertail', 43);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (35, '317.67', 'Lion, steller sea', 79);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (37, '284.66', 'Huron', 16);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (1, '176.06', 'Dassie', 32);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (6, '104.62', 'Puma, south american', 44);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (11, '334.28', 'Cockatoo, roseate', 57);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (39, '179.61', 'Kingfisher, malachite', 95);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (14, '88.43', 'American Virginia opossum', 87);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (8, '199.32', 'White stork', 15);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (27, '332.45', 'Bohor reedbuck', 49);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (23, '291.62', 'Rat, arboral spiny', 87);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (33, '10.90', 'Southern screamer', 60);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (14, '161.85', 'Vulture, bengal', 55);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (43, '127.40', 'Argalis', 25);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (4, '124.61', 'Weaver, white-browed sparrow', 71);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (48, '311.74', 'Sockeye salmon', 21);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (19, '126.00', 'Black-tailed tree creeper', 99);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (34, '54.24', 'Greater flamingo', 3);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (31, '197.65', 'Cat, civet', 5);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (19, '55.63', 'Hummingbird (unidentified)', 82);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (22, '298.62', 'Hoopoe, eurasian', 45);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (30, '86.21', 'Hyena, striped', 75);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (49, '231.91', 'Kori bustard', 53);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (27, '25.99', 'Red meerkat', 57);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (44, '348.73', 'Kangaroo, black-faced', 83);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (35, '95.24', 'Sheep, red', 87);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (8, '83.13', 'Yellow-rumped siskin', 18);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (34, '262.48', 'Hawk-eagle, crowned', 37);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (27, '22.24', 'Monkey, bleeding heart', 23);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (46, '272.45', 'Stone sheep', 2);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (30, '255.00', 'Egret, great', 50);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (30, '273.21', 'Puma', 32);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (3, '140.03', 'Mongoose, small indian', 11);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (30, '307.22', 'Grouse, greater sage', 17);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (8, '89.54', 'Malabar squirrel', 78);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (4, '68.07', 'Otter, giant', 48);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (20, '61.36', 'Brocket, red', 9);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (5, '104.06', 'Dassie', 73);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (29, '199.51', 'Porcupine, indian', 97);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (11, '203.10', 'Bee-eater, white-fronted', 17);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (19, '230.25', 'Badger, american', 56);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (38, '208.07', 'Legaan, Monitor (unidentified)', 57);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (27, '48.77', 'Phalarope, red', 14);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (42, '138.37', 'Red-billed tropic bird', 78);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (49, '342.43', 'Common langur', 79);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (31, '282.77', 'Puffin, horned', 38);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (45, '16.40', 'Peacock, indian', 27);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (15, '261.27', 'Bird, pied butcher', 91);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (5, '127.34', 'Greater roadrunner', 80);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (14, '49.75', 'Zebra, plains', 93);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (26, '191.22', 'Lizard, blue-tongued', 35);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (29, '11.60', 'Tiger snake', 42);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (37, '336.26', 'Green heron', 84);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (30, '51.42', 'Monitor, water', 51);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (1, '318.40', 'Gray heron', 60);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (47, '341.02', 'Elegant crested tinamou', 98);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (21, '208.15', 'Seal, southern elephant', 29);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (16, '73.34', 'Barbet, crested', 26);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (38, '260.99', 'Springhare', 32);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (7, '83.90', 'Gazelle, grant''s', 33);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (48, '38.77', 'Squirrel, smith''s bush', 31);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (30, '130.57', 'Black-tailed tree creeper', 42);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (32, '78.47', 'Phalarope, red', 97);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (6, '76.74', 'Ring-tailed gecko', 12);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (9, '259.59', 'Savanna baboon', 35);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (46, '253.22', 'Cat, kaffir', 75);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (20, '205.34', 'Eagle, tawny', 89);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (47, '291.79', 'Barasingha deer', 83);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (40, '180.40', 'Goose, cereopsis', 90);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (47, '80.16', 'Blue duck', 45);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (4, '136.24', 'Blue crane', 65);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (28, '227.22', 'Mocking cliffchat', 84);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (26, '309.85', 'Sloth, pale-throated three-toed', 44);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (42, '254.72', 'Sable antelope', 66);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (14, '31.35', 'Albatross, galapagos', 16);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (9, '152.29', 'Sidewinder', 23);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (17, '306.14', 'Goose, cape barren', 18);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (40, '334.31', 'Southern black-backed gull', 3);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (3, '145.92', 'Golden brush-tailed possum', 30);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (17, '284.92', 'Pigeon, feral rock', 34);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (48, '150.74', 'Coqui partridge', 36);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (13, '330.11', 'Eastern boa constrictor', 47);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (34, '146.07', 'Sockeye salmon', 34);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (8, '211.40', 'Two-banded monitor', 73);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (37, '10.35', 'Rhesus monkey', 92);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (34, '165.40', 'Bustard, denham''s', 71);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (48, '295.24', 'Owl, burrowing', 76);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (47, '318.22', 'Colobus, magistrate black', 98);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (20, '163.35', 'Lion, mountain', 35);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (20, '203.86', 'Cape fox', 65);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (21, '10.38', 'White stork', 22);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (4, '311.71', 'Black-fronted bulbul', 14);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (45, '174.67', 'Tern, arctic', 32);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (14, '148.30', 'Green-backed heron', 10);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (2, '160.83', 'Snowy owl', 74);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (14, '65.34', 'Stone sheep', 48);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (35, '268.10', 'Moccasin, water', 89);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (12, '88.55', 'Boat-billed heron', 36);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (3, '135.42', 'Red-shouldered glossy starling', 70);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (14, '240.25', 'Eastern dwarf mongoose', 99);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (32, '54.13', 'Vulture, white-rumped', 83);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (45, '139.21', 'Marine iguana', 96);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (3, '310.02', 'Common grenadier', 48);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (7, '238.24', 'Cape white-eye', 10);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (13, '166.43', 'Hedgehog, south african', 48);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (1, '132.15', 'Slender loris', 44);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (18, '331.67', 'Shrike, crimson-breasted', 86);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (20, '234.56', 'Squirrel, uinta ground', 22);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (41, '307.35', 'Black-eyed bulbul', 60);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (26, '144.99', 'Madagascar hawk owl', 33);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (32, '246.60', 'Boa, mexican', 41);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (46, '103.63', 'Indian leopard', 26);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (13, '164.13', 'Flycatcher, tyrant', 39);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (43, '89.25', 'Monitor, two-banded', 26);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (36, '246.19', 'Capuchin, weeper', 71);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (30, '297.01', 'Two-toed tree sloth', 4);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (4, '155.26', 'Burmese black mountain tortoise', 58);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (10, '152.23', 'Tawny eagle', 81);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (47, '64.27', 'Ostrich', 97);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (8, '334.22', 'Langur, gray', 65);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (28, '11.88', 'Grant''s gazelle', 51);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (33, '36.04', 'Laughing kookaburra', 11);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (32, '105.64', 'Snake, eastern indigo', 91);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (45, '335.37', 'Saddle-billed stork', 31);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (28, '75.04', 'Euro wallaby', 77);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (50, '168.34', 'Neotropic cormorant', 15);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (13, '228.02', 'Hanuman langur', 1);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (25, '34.75', 'Collared lizard', 13);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (40, '216.48', 'Pelican, brown', 25);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (31, '339.35', 'Red-winged hawk (unidentified)', 45);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (12, '72.06', 'Loris, slender', 80);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (5, '186.63', 'Ring-tailed coatimundi', 79);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (29, '157.60', 'Barasingha deer', 75);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (4, '196.84', 'Hanuman langur', 7);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (22, '178.02', 'Jaguarundi', 90);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (40, '139.62', 'Thomson''s gazelle', 33);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (31, '322.19', 'Malachite kingfisher', 48);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (17, '330.50', 'Southern boubou', 39);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (36, '34.43', 'Eastern fox squirrel', 2);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (7, '23.84', 'Blue-tongued lizard', 60);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (50, '69.95', 'Grey mouse lemur', 32);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (42, '183.63', 'Rufous tree pie', 28);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (43, '43.63', 'White-faced whistling duck', 90);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (45, '70.22', 'Yellow baboon', 31);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (50, '20.36', 'Bird, red-billed tropic', 25);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (9, '64.03', 'Crane, black-crowned', 33);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (46, '153.57', 'Partridge, coqui', 14);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (27, '330.74', 'White-faced tree rat', 72);
insert into book (Author_amazon_idAuthor_amazon, price, title, stock) values (7, '168.60', 'Penguin, galapagos', 41);
