insert into Plane (capacitat, model) values (130, 'Viper');
insert into Plane (capacitat, model) values (90, 'Marauder');
insert into Plane (capacitat, model) values (61, 'ES');
insert into Plane (capacitat, model) values (32, 'XC90');
insert into Plane (capacitat, model) values (174, 'Pathfinder');
insert into Plane (capacitat, model) values (126, 'Ram Van 2500');
insert into Plane (capacitat, model) values (26, 'Escalade');
insert into Plane (capacitat, model) values (66, 'Firebird');
insert into Plane (capacitat, model) values (43, 'C-Class');
insert into Plane (capacitat, model) values (87, 'CLK-Class');
insert into Plane (capacitat, model) values (33, 'Mohave/Borrego');
insert into Plane (capacitat, model) values (153, 'Blazer');
insert into Plane (capacitat, model) values (133, 'Monza');
insert into Plane (capacitat, model) values (32, 'Pajero');
insert into Plane (capacitat, model) values (48, 'IS-F');
insert into Plane (capacitat, model) values (111, 'Caravan');
insert into Plane (capacitat, model) values (115, 'MX-5');
insert into Plane (capacitat, model) values (37, 'Cirrus');
insert into Plane (capacitat, model) values (53, 'RX');
insert into Plane (capacitat, model) values (74, 'Ranger');
insert into Plane (capacitat, model) values (144, 'Grand Prix');
insert into Plane (capacitat, model) values (106, 'F350');
insert into Plane (capacitat, model) values (102, 'Grand Cherokee');
insert into Plane (capacitat, model) values (49, 'Alcyone SVX');
insert into Plane (capacitat, model) values (28, 'Malibu');
insert into Plane (capacitat, model) values (67, 'Protege5');
insert into Plane (capacitat, model) values (89, 'Explorer');
insert into Plane (capacitat, model) values (145, 'Rally Wagon 2500');
insert into Plane (capacitat, model) values (38, 'Sprinter 2500');
insert into Plane (capacitat, model) values (81, 'Colorado');
insert into Plane (capacitat, model) values (72, 'Focus');
insert into Plane (capacitat, model) values (142, 'Reno');
insert into Plane (capacitat, model) values (75, 'E350');
insert into Plane (capacitat, model) values (159, '62');
insert into Plane (capacitat, model) values (65, 'Sephia');
insert into Plane (capacitat, model) values (117, 'Silverado 1500');
insert into Plane (capacitat, model) values (105, '5000S');
insert into Plane (capacitat, model) values (74, 'V70');
insert into Plane (capacitat, model) values (126, 'Range Rover');
insert into Plane (capacitat, model) values (105, 'Esprit');
insert into Plane (capacitat, model) values (72, 'LeSabre');
insert into Plane (capacitat, model) values (163, 'Discovery');
insert into Plane (capacitat, model) values (189, '6 Series');
insert into Plane (capacitat, model) values (78, 'G35');
insert into Plane (capacitat, model) values (59, 'Suburban 1500');
insert into Plane (capacitat, model) values (94, 'Savana');
insert into Plane (capacitat, model) values (49, 'H1');
insert into Plane (capacitat, model) values (134, 'Ram 50');
insert into Plane (capacitat, model) values (49, 'Focus');
insert into Plane (capacitat, model) values (175, 'LaCrosse');
